### ISSUE TITLE
I.E. 9 Button Not Showing

### ISSUE THREAD

**Issue by teknology** [amzn/amazon-payments-magento-plugin#108]
I've noticed that in I.E. 9 the amazon payments button does not show on the checkout page. When viewing the issue in inspector i found an error.
Object doesn't support property or method 'addEventListener' for G.addEventListener("load",N,false);if

**Comment by jonahellison** [comment]
Hi teknology, do you know what file is causing this error?

**Comment by ngrices** [comment]
In older versions of IE9 where the merchant is leveraging a 2.X version of jquery, the button may appear to 'do nothing' when clicked ot it may cause the button not to appear at all. In reality there are console errors in JavaScript thrown that will say something like "Object doesn't support property or method 'addEventListener'" 
This is caused by jquery 2.X explicitly dropping support for IE8/9 and its use of the method addEventListener 
To fix this problem, have the merchant add the following line to the head section of  any page containing the button
<meta http-equiv="X-UA-Compatible" content="IE=edge;" />
See here for more information
https://forum.jquery.com/topic/jquery-2-1-1-min-js-object-doesn-t-support-property-or-method-addeventlistener

teknology, can you give this a try?
