### ISSUE TITLE
LPA blocking Magento Global Messages

### ISSUE THREAD

**Issue by mckeej** [amzn/amazon-payments-magento-plugin#161]
When LPA is active on the cart page it does not show Magento Global Messages. When entering in an incorrect coupon code on the cart page the message alerting the customer that the code was incorrect does not show. When LPA module is disabled the global message appears alerting the customer the coupon code was incorrect.

Customer Message:
"Hi,

I’ve been trying to troubleshoot a problem with our cart and realized today that it is tied to the Amazon Payments module. I think the Magento term is ‘global messages’, but when someone gets an error or success message on the cart page, like this screenshot below, it just does not appear when Amazon Payments module is enabled.

This has been confusing to customers who are getting no errors or success messages after submitting a coupon code or being redirected to the cart after an unsuccessful checkout, etc. It’s not related to our theme because I get the same problem with the default Magento theme."

**Comment by ngrices** [comment]
@mckeej can you ask the customer 2 questions
1) a screenshot of a normal message 
2) what theme he is using.

**Comment by chugginn** [comment]
Hi, client here. Here's a link to download 4 sets of files to review:

https://s3-us-west-2.amazonaws.com/be-misc/amz-global-messages-issue.zip

We're using a custom theme. The files, a screenshot and source code capture, are as follows:

1. **Custom Theme, Amazon Payments Enabled**: This is our default setting. After submitting non-existent coupon code 'asdf' I captured this screenshot and source code. No global message appears.
2. **Custom Theme Amazon Payments Disabled**: After submitting non-existent coupon code 'asdf' note that global message appears, "Coupon Code does not exist"
3. **Default Theme, Amazon Payments Enabled**: After submitting non-existent coupon code 'asdf', no global message appears.
4. **Default Theme Amazon Payments Disabled**: After submitting non-existent coupon code 'asdf' note that global message appears, "Coupon Code does not exist"

This issue is related to not just coupon codes, rather global messages as a whole.

**Comment by jonahellison** [comment]
Hi @chugginn, do you know if any changes were made to amazon_payments.xml? (I am having trouble reproducing this locally. I also get a different error message: Coupon code "asdf" is not valid)

**Comment by chugginn** [comment]
I haven't made any changes, but I noticed our amazon_payments.xml is considerably different from the one in this repository. What is the best way to update our module?

**Comment by chugginn** [comment]
OK - I uploaded the newest version files (1.2) to overwrite all existing files on a dev installation (login credentials sent separately), and the global message is showing up now. However a new issue is that there are a ton of new javascript errors, one for example does not allow the Apply Coupon button to be clicked at the cart page (have to press enter to submit it). This occurs both with current theme and default theme.
