### ISSUE TITLE
Unable to configure settings, missing info, buttons underneath display:none ?

### ISSUE THREAD

**Issue by kayintveen** [amzn/amazon-payments-magento-plugin#264]
Currently i am trying to get this working. After installation i ended up with something different then the documentation shows:

![image of my result]
(https://photos-1.dropbox.com/t/2/AAAcAjslG7EA_sd7jqyfjBvfbJZnEE1FXCVJULlrsUtSRA/12/359125/png/32x32/3/1463533200/0/2/Screenshot%202016-05-17%2022.20.12.png/EKmoPBjcrZf4AyACKAI/IGlDaLJIJLestyptaGCztDNmQLFFNQx_tEvYwXtnFtQ?size_mode=3&size=2048x1536)

**Comment by islandskater43** [comment]
We've seen a couple issues of this get reported through Magento connect as well.

**Comment by islandskater43** [comment]
@kayintveen - what version were you guys on of Magento?

**Comment by jonahellison** [comment]
Due to the number of config options, nested fieldsets were used in the admin, which unfortunately is only supported by Magento 1.7+.

As a workaround, /app/code/community/Amazon/Payments/etc/system.xml will need to be replaced with the 1.6 version:

https://raw.githubusercontent.com/amzn/amazon-payments-magento-plugin/master/app/code/community/Amazon/Payments/etc/system.xml-1.6

**Comment by jonahellison** [comment]
Updated Wiki/FAQ with this solution for "broken config."
