### ISSUE TITLE
Magestore One Step Checkout

### ISSUE THREAD

**Issue by snoroozi** [amzn/amazon-payments-magento-plugin#288]
We are trying to get this working with magestore one step checkout.  Currently we're able to get it to show under payment methods.  But not really sure what the recommended flow or integration would be?

Do you already have a solution for this extension, and can you please let me know exactly how it is to work?

**Comment by islandskater43** [comment]
With unsupported checkouts, the easiest integration option is to incorporate the script block (script.phtml) and the button block (button.phtml), so that the Pay with Amazon button will appear on the checkout. This would ideally be surfaced as early in the checkout flow as possible, in order to provide as much benefit to the buyer/customer as possible.

Here's an example of the front-end layout xml file for OneStepCheckout offered @ onestepcheckout.com:
https://github.com/amzn/amazon-payments-magento-plugin/blob/master/app/design/frontend/base/default/layout/amazon_payments.xml#L344-L377

From a settings perspective, you then need to make sure that the Pay with Amazon module is set to use the Amazon Standalone checkout. The expected behavior in the end would be to see the button on the Magestore One Step Checkout page. Clicking the button will trigger the Amazon login. After login, they will be redirected to the Amazon Standalone checkout where the Amazon widgets will be pulled in and the buyer can complete their checkout.

**Comment by islandskater43** [comment]
@snoroozi - was the above information helpful? Can we provide any more information to help resolve?

**Comment by snoroozi** [comment]
I'll have to revisit this after cyber Monday. Decided not to implement new
checkout this close to game time.

**Comment by islandskater43** [comment]
Understood. Please reopen or create a new issue if you have further questions. Thanks!
