### ISSUE TITLE
After clicking on "Place Order" alert box shown with error.

### ISSUE THREAD

**Issue by nicklera1** [amzn/amazon-payments-magento-plugin#296]
```
exception 'Mage_Core_Exception' with message 'Please check shipping address information. Please enter the first name. Please enter the last name. Please enter the street.' in /home/*REMOVED*/public_html/app/Mage.php:595

Stack trace:
#0 /home/*REMOVED*/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(298): Mage::throwException('Please check sh...')

#1 /home/*REMOVED*/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(222): Mage_Sales_Model_Service_Quote->_validate()

#2 /home/*REMOVED*/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(238): Mage_Sales_Model_Service_Quote->submitNominalItems()
#3 /home/*REMOVED*/public_html/app/code/community/Amazon/Payments/Model/Type/Checkout.php(120): Mage_Sales_Model_Service_Quote->submitAll()
#4 /home/*REMOVED*/public_html/app/code/community/Amazon/Payments/controllers/CheckoutController.php(235): Amazon_Payments_Model_Type_Checkout->saveOrder()
#5 /home/*REMOVED*/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Amazon_Payments_CheckoutController->saveOrderAction()
#6 /home/*REMOVED*/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#7 /home/*REMOVED*/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /home/*REMOVED*/public_html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /home/*REMOVED*/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /home/*REMOVED*/public_html/index.php(62): Mage::run('', 'store')
#11 {main}
```
![image001 copy](https://cloud.githubusercontent.com/assets/20075335/20278982/9d255658-aa5b-11e6-9d37-e2ef420c0b34.png)

**Comment by islandskater43** [comment]
The fields identified in the validation error are the fields that are suppressed from the GetOrderReferenceDetails response when the access token is omitted from the API request, which makes me think the cause is a missing access token. 

We should take the following actions to work to resolve this:
 - proactively review the code to try to determine a code path wherein the access token is not supplied to the GetOrderReferenceDetails call
 - add additional logging when the getOrderReferenceDetails call is made and no access token is passed
 - add additional logging when setting address information in the quote but name and street information doesn't exist in the API call response

**Comment by jonahellison** [comment]
Added additional logging. One thing to note is that this Magento error message is rather cryptic and can be caused by malformed addresses, even if one field is missing. If this occurs again, it would be best to:
1. Try to repo by using the given address
2. Try a different address and see if it works

**Comment by gbear** [comment]
We noticed that the issues appears to be resolved for Firefox, but in Chrome we’re still seeing a jQuery conflict causing the shipping method box to disappear.

**Comment by jonahellison** [comment]
Can't repro in latest version of Chrome.
