### ISSUE TITLE
PHP 7 issue with Import From Clipboard

### ISSUE THREAD

**Issue by cbend** [amzn/amazon-payments-magento-plugin#305]
I follow the instructions to "My account is ready, I need to connect it to Magento" and I get the following error when I try to save "Import From Clipboard": "PHP Fatal error: Uncaught Error: Call to undefined function mcrypt_cbc()". The error is because mcrypt_cbc() is removed in PHP 7. I am just seeing if anybody else has run into this. If so, do you have a fix for it?

Thanks in advance

**Comment by jochhop** [comment]
Any updates in this issue?

**Comment by islandskater43** [comment]
Hi @cbend & @jochhop - Thanks for raising this issue. With the mcrypt library being removed in PHP7, you can follow the steps in our [Manual Key Transfer](https://pay.amazon.com/us/help/202024240) guide. Rather than copying the JSON object into the `Import from Clipboard` field, copy the individual keys into their respective fields. 

If you run into any further issues, please comment on this issue.

**Comment by islandskater43** [comment]
Closing in favor of #318 to resolve the `mcrypt_cbc` issue.

**Comment by islandskater43** [comment]
Actually, @cbend or @jochhop -- would either of you mind making the edit recommended in #318 and seeing if it works for you then?
