### ISSUE TITLE
mcrypt_cbc removed in PHP7

### ISSUE THREAD

**Issue by islandskater43** [amzn/amazon-payments-magento-plugin#318]
The mcrypt_cbc function was removed in PHP7. This is causing setup issues for merchants using PHP7 for their instance.

**Comment by islandskater43** [comment]
The code change needs to be made at [line 142 of SimplePath.php](https://github.com/amzn/amazon-payments-magento-plugin/blob/2f85755a4b870cd53bc412de735d0bc3b04c7757/app/code/community/Amazon/Payments/Model/SimplePath.php#L142).

**Comment by islandskater43** [comment]
Current line 142:
```$finalPayload = mcrypt_cbc(MCRYPT_RIJNDAEL_128, $decryptedKey, base64_decode($payload->encryptedPayload), MCRYPT_DECRYPT, base64_decode($payload->iv));```

Possible replacement:
```$finalPayload = mcrypt_decrypt(MCRYPT_RIJNDAEL_128, $decryptedKey, base64_decode($payload->encryptedPayload), MCRYPT_MODE_CBC, base64_decode($payload->iv));```

**Comment by pronto2000** [comment]
It works, but since mcrypt_decrypt is also deprecated (as of PHP 7.1), then it's just postponing the inevitable. I recommend openssl_decrypt instead:

`$finalPayload = rtrim(openssl_decrypt(base64_decode($payload->encryptedPayload), 'aes-128-cbc', $key, OPENSSL_RAW_DATA | OPENSSL_NO_PADDING, base64_decode($payload->iv)), "\0");`

**Comment by islandskater43** [comment]
Resolved by 71462b3
